"""
generate_readme.py
──────────────────
Injects the three SVG cards into README.md using HTML comment markers.

  Layout:
    ┌─────────────────────────────────────┐
    │  terminal-card  │   info-card        │
    └─────────────────────────────────────┘
         github-contribution-animation
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import OUT_README, OUT_CONTRIB, OUT_TERMINAL, OUT_INFO, USERNAME, DISPLAY_NAME

MARKER_START = "<!-- PROFILE-START -->"
MARKER_END   = "<!-- PROFILE-END -->"


def _rel(path: str) -> str:
    """Convert absolute path to repo-relative path for the Markdown link."""
    root = os.path.dirname(os.path.abspath(__file__))
    rel = os.path.relpath(path, root).replace("\\", "/")
    return rel


def _build_injection(
    terminal_path: str,
    info_path: str,
    contrib_path: str,
) -> str:
    tc = _rel(terminal_path)
    ic = _rel(info_path)
    cc = _rel(contrib_path)

    return f"""{MARKER_START}

<div align="center">

<!-- Terminal ASCII Portrait -->
<img src="{tc}" alt="Terminal ASCII Portrait" width="600"/>
<br/><br/>

<!-- Neofetch Info Card -->
<img src="{ic}" alt="Neofetch Info Card" width="820"/>
<br/><br/>

<!-- Contribution Graph -->
<img src="{cc}" alt="GitHub Contribution Graph" width="900"/>

</div>

{MARKER_END}"""


def inject(
    readme_path: str = OUT_README,
    terminal_path: str = OUT_TERMINAL,
    info_path: str     = OUT_INFO,
    contrib_path: str  = OUT_CONTRIB,
) -> None:
    injection = _build_injection(terminal_path, info_path, contrib_path)

    # Read or bootstrap README
    if os.path.exists(readme_path):
        with open(readme_path, "r", encoding="utf-8") as f:
            content = f.read()
    else:
        content = _default_readme()

    if MARKER_START in content and MARKER_END in content:
        # Replace between markers
        before = content[:content.index(MARKER_START)]
        after  = content[content.index(MARKER_END) + len(MARKER_END):]
        new_content = before + injection + after
    else:
        # Prepend the block if markers are missing
        new_content = injection + "\n\n" + content

    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(new_content)

    print(f"[✓] README updated: {readme_path}")


def _default_readme() -> str:
    return f"""# {DISPLAY_NAME}

{MARKER_START}
{MARKER_END}

---

> Generated by the KHUSHAL SINGH SANKHLA
"""


if __name__ == "__main__":
    inject()
