"""
generate_readme.py
──────────────────
Injects the three SVG cards into README.md using HTML comment markers.
All SVG images (including the contribution graph) are clickable links to the user's GitHub profile/contributions.

  Layout: 1:4 ratio horizontal cards (250px vs 650px)
    ┌───────────────────────┬─────────────────────────────────────────────────────────┐
    │ terminal-card.svg 250 │                   info-card.svg 650                     │
    └───────────────────────┴─────────────────────────────────────────────────────────┘
                               github-contribution-animation.svg 900
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import OUT_README, OUT_CONTRIB, OUT_TERMINAL, OUT_INFO, USERNAME, DISPLAY_NAME

MARKER_START = "<!-- GITHUB-ASSETS-START -->"
MARKER_END   = "<!-- GITHUB-ASSETS-END -->"

LEGACY_START = "<!-- PROFILE-START -->"
LEGACY_END   = "<!-- PROFILE-END -->"


def _rel(path: str) -> str:
    """Convert absolute path to repo-relative path for the Markdown link."""
    root = os.path.dirname(os.path.abspath(__file__))
    rel = os.path.relpath(path, root).replace("\\", "/")
    return rel


def _build_injection(
    terminal_path: str,
    info_path: str,
    contrib_path: str,
) -> str:
    tc = _rel(terminal_path)
    ic = _rel(info_path)
    cc = _rel(contrib_path)

    profile_url = f"https://github.com/{USERNAME}"
    contrib_url = f"https://github.com/{USERNAME}?tab=overview"

    return (
        f"{MARKER_START}\n"
        '<p align="center">\n'
        "<table>\n"
        "<tr>\n"
        f'<td width="250" align="center" valign="top"><a href="{profile_url}"><img src="{tc}" alt="Terminal ASCII Portrait" width="250"/></a></td>\n'
        f'<td width="650" align="center" valign="top"><a href="{profile_url}"><img src="{ic}" alt="Neofetch Info Card" width="650"/></a></td>\n'
        "</tr>\n"
        "</table>\n"
        "</p>\n\n"
        '<p align="center">\n'
        f'  <a href="{contrib_url}"><img src="{cc}" alt="GitHub Contribution Graph" width="900"/></a>\n'
        "</p>\n"
        f"{MARKER_END}"
    )


def inject(
    readme_path: str = OUT_README,
    terminal_path: str = OUT_TERMINAL,
    info_path: str     = OUT_INFO,
    contrib_path: str  = OUT_CONTRIB,
) -> None:
    injection = _build_injection(terminal_path, info_path, contrib_path)

    if os.path.exists(readme_path):
        with open(readme_path, "r", encoding="utf-8") as f:
            content = f.read()
    else:
        content = _default_readme()

    # Strip legacy markers if present to avoid duplication
    if LEGACY_START in content and LEGACY_END in content:
        before_legacy = content[:content.index(LEGACY_START)]
        after_legacy = content[content.index(LEGACY_END) + len(LEGACY_END):]
        content = (before_legacy.strip() + "\n\n" + after_legacy.strip()).strip()

    # Inject or replace inside GITHUB-ASSETS markers
    if MARKER_START in content and MARKER_END in content:
        before = content[:content.index(MARKER_START)]
        after  = content[content.index(MARKER_END) + len(MARKER_END):]
        new_content = before.rstrip() + "\n\n" + injection + "\n\n" + after.lstrip()
    else:
        # Prepend after first title heading if present, else at top
        lines = content.splitlines()
        header_idx = -1
        for idx, line in enumerate(lines):
            if line.startswith("#"):
                header_idx = idx
                break
        if header_idx != -1:
            lines.insert(header_idx + 1, "\n" + injection + "\n")
            new_content = "\n".join(lines)
        else:
            new_content = injection + "\n\n" + content

    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(new_content.strip() + "\n")

    print(f"[✓] README updated: {readme_path}")


def _default_readme() -> str:
    return f"""# {DISPLAY_NAME}

{MARKER_START}
{MARKER_END}

---

> Generated by the KHUSHAL SINGH SANKHLA
"""


if __name__ == "__main__":
    inject()
